#!/bin/bash
# Dosmildos DNSTT Termux Script Installer
#--------------------------------

# Clean up any previous installation
rm -rf install

# Update package lists and install required packages
apt-get update
apt-get install -y dnsutils nano

# Download the menu script to the correct path
wget --no-check-certificate -O /data/data/com.termux/files/usr/bin/menu https://raw.githubusercontent.com/JBPH08/test-termux/main/menu

# Make the menu script executable
chmod +x /data/data/com.termux/files/usr/bin/menu

# Completion messages
echo "Installation Completed."
echo
echo "Dosmildos DNSTT Script v0.1.4.6"
echo "https://phcorner.net/members/arjienx.1773652/"
echo
echo "Dosmildos"
echo "Press 'enter' to back and start query testing instantly."
echo "Type 'menu' to run the dnstt termux script."
